name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    setup:
        name: CI

        runs-on: ubuntu-latest

        steps:
            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install ffmpeg

            - name: Setup Node
              uses: actions/setup-node@v2-beta
              with:
                  node-version: 10.x

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Yarn Dependencies
              run: |
                  yarn
                  cd gulp/
                  yarn
                  cd ..
            - name: Lint
              run: |
                  yarn lint
            - name: TSLint
              run: |
                  cd gulp
                  yarn gulp translations.fullBuild
                  yarn gulp localConfig.findOrCreate
                  cd ..
                  yarn tslint

    yaml-lint:
        name: yaml-lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: YAML Lint
              uses: ibiqlik/action-yamllint@v1.0.0
              with:
                  file_or_dir: translations/*.yaml

    create-mod:
        name: create-mod

        needs: setup
        if: ${{ github.event_name == 'push' }}

        runs-on: ubuntu-latest

        steps:
            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install ffmpeg

            - name: Setup Node
              uses: actions/setup-node@v2-beta
              with:
                  node-version: 10.x

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Yarn Dependencies
              run: |
                  yarn
                  cd gulp/
                  yarn
                  cd ..

            - name: Building mod development version
              run: |
                  cd gulp
                  yarn gulp build.mod

            - name: Getting commit hash
              id: hash
              run: echo "::set-output name=short::$(git rev-parse --short HEAD)"

            - name: Creating build artifact
              uses: actions/upload-artifact@v2
              with:
                  name: shapezio-mod-build-${{ steps.hash.outputs.short }}
                  path: "/build"
                  if-no-files-found: error
